notifications:
  email:
    - takenory@gmail.com
  on_success: always # default: change
  on_failure: always # default: always
rvm:
  - 1.9.2
env:
  - DB=postgres
script: "bundle exec rake db:create db:migrate spec"
